# -*- coding: utf-8 -*-
"""graph1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BZtdoC6NETTa08-m6Ykv-4Nbsz90yUL4
"""

import matplotlib.pyplot as plt

# Data for Set Size, Merge Sort Time, and Quick Sort Time
set_size = [1000, 5000, 10000, 50000, 100000]
merge_sort_time = [0.000000, 0.001000, 0.000000, 0.016000, 0.026000]
quick_sort_time = [0.000000, 0.000000, 0.003000, 0.007000, 0.022000]

# Create the plot
plt.figure(figsize=(10, 6))

# Plot the Merge Sort Time vs Set Size
plt.plot(set_size, merge_sort_time, label='Merge Sort Time', marker='o', color='blue', linestyle='-', linewidth=2)

# Plot the Quick Sort Time vs Set Size
plt.plot(set_size, quick_sort_time, label='Quick Sort Time', marker='o', color='red', linestyle='-', linewidth=2)

# Add labels and title
plt.xlabel('Set Size')
plt.ylabel('Time (seconds)')
plt.title('Performance Comparison: Merge Sort vs Quick Sort')

# Add a legend
plt.legend()

# Add grid for better readability
plt.grid(True)

# Display the plot
plt.show()